Remove unnecessary C99 mode requirement
Fix compilation error when C99 mode is not enabled. For example :
../src/mbedtls/mbedtls-2.28.3/library/oid.c: In function ‘mbedtls_oid_get_numeric_string’:
../src/mbedtls/mbedtls-2.28.3/library/oid.c:797: error: ‘for’ loop initial declaration used outside C99 mode

It is only used in 3 places in whole MbedTLS code.